const sampleData = {
    totalUsers: [
      { user_id: 1, userName: 'johndoe', Name: 'John Doe', Email: 'john.doe@example.com' },
      { user_id: 2, userName: 'janedoe', Name: 'Jane Doe', Email: 'jane.doe@example.com' },
      { user_id: 3, userName: 'mikesmith', Name: 'Mike Smith', Email: 'mike.smith@example.net' },
      { user_id: 4, userName: 'sarahjones', Name: 'Sarah Jones', Email: 'sarah.jones@domain.org' },
      { user_id: 5, userName: 'alexjohnson', Name: 'Alex Johnson', Email: 'alex.johnson@example.io' },
      { user_id: 6, userName: 'emilydavis', Name: 'Emily Davis', Email: 'emily.davis@example.co' },
      { user_id: 7, userName: 'chrismartin', Name: 'Chris Martin', Email: 'chris.martin@company.com' },
      { user_id: 8, userName: 'lindawilson', Name: 'Linda Wilson', Email: 'linda.wilson@webmail.com' },
      { user_id: 9, userName: 'kevinbrown', Name: 'Kevin Brown', Email: 'kevin.brown@techcorp.com' },
      { user_id: 10, userName: 'sophiamiller', Name: 'Sophia Miller', Email: 'sophia.miller@example.com' },
      { user_id: 11, userName: 'williamthomas', Name: 'William Thomas', Email: 'william.thomas@domain.net' },
      { user_id: 12, userName: 'oliviaanderson', Name: 'Olivia Anderson', Email: 'olivia.anderson@example.org' },
      { user_id: 13, userName: 'davidmoore', Name: 'David Moore', Email: 'david.moore@internet.com' },
      { user_id: 14, userName: 'elizabethmartinez', Name: 'Elizabeth Martinez', Email: 'elizabeth.martinez@webmail.io' },
      { user_id: 15, userName: 'jameslopez', Name: 'James Lopez', Email: 'james.lopez@domain.com' },
      { user_id: 16, userName: 'amandaclark', Name: 'Amanda Clark', Email: 'amanda.clark@company.net' },
      { user_id: 17, userName: 'danielhill', Name: 'Daniel Hill', Email: 'daniel.hill@webmail.org' },
      { user_id: 18, userName: 'lisawright', Name: 'Lisa Wright', Email: 'lisa.wright@example.io' },
      { user_id: 19, userName: 'josephgreen', Name: 'Joseph Green', Email: 'joseph.green@company.co' },
      { user_id: 20, userName: 'melissalee', Name: 'Melissa Lee', Email: 'melissa.lee@webmail.com' },
      { user_id: 21, userName: 'michaelking', Name: 'Michael King', Email: 'michael.king@techcorp.com' },
      { user_id: 22, userName: 'brittanyperez', Name: 'Brittany Perez', Email: 'brittany.perez@domain.com' },
      { user_id: 23, userName: 'briankelly', Name: 'Brian Kelly', Email: 'brian.kelly@internet.net' },
      { user_id: 24, userName: 'lauragarcia', Name: 'Laura Garcia', Email: 'laura.garcia@webmail.org' },
      { user_id: 25, userName: 'ryanmartin', Name: 'Ryan Martin', Email: 'ryan.martin@company.io' },
      { user_id: 26, userName: 'nicolewhite', Name: 'Nicole White', Email: 'nicole.white@webmail.co' },
      { user_id: 27, userName: 'kylejohnson', Name: 'Kyle Johnson', Email: 'kyle.johnson@domain.com' },
      { user_id: 28, userName: 'meganallen', Name: 'Megan Allen', Email: 'megan.allen@techcorp.com' },
      { user_id: 29, userName: 'markyoung', Name: 'Mark Young', Email: 'mark.young@example.com' },
      { user_id: 30, userName: 'ashleyhernandez', Name: 'Ashley Hernandez', Email: 'ashley.hernandez@domain.net' },
      { user_id: 31, userName: 'stevenlee', Name: 'Steven Lee', Email: 'steven.lee@webmail.org' },
      { user_id: 32, userName: 'kimberlymartinez', Name: 'Kimberly Martinez', Email: 'kimberly.martinez@internet.io' },
      { user_id: 33, userName: 'richardclark', Name: 'Richard Clark', Email: 'richard.clark@domain.com' },
      { user_id: 34, userName: 'angelawright', Name: 'Angela Wright', Email: 'angela.wright@company.net' },
      { user_id: 35, userName: 'jeffreyhall', Name: 'Jeffrey Hall', Email: 'jeffrey.hall@techcorp.org' },
      { user_id: 36, userName: 'amberwilson', Name: 'Amber Wilson', Email: 'amber.wilson@webmail.io' },
      { user_id: 37, userName: 'andrewrodriguez', Name: 'Andrew Rodriguez', Email: 'andrew.rodriguez@company.co' },
      { user_id: 38, userName: 'jennifergreen', Name: 'Jennifer Green', Email: 'jennifer.green@webmail.com' },
      { user_id: 39, userName: 'patricklee', Name: 'Patrick Lee', Email: 'patrick.lee@techcorp.com' },
      { user_id: 40, userName: 'victoriahernandez', Name: 'Victoria Hernandez', Email: 'victoria.hernandez@domain.com' },
      { user_id: 41, userName: 'brandonking', Name: 'Brandon King', Email: 'brandon.king@internet.net' },
      { user_id: 42, userName: 'heatherclark', Name: 'Heather Clark', Email: 'heather.clark@webmail.org' },
      { user_id: 43, userName: 'joewilliams', Name: 'Joe Williams', Email: 'joe.williams@company.io' },
      { user_id: 44, userName: 'mariaroberts', Name: 'Maria Roberts', Email: 'maria.roberts@webmail.co' },
      { user_id: 45, userName: 'larrywhite', Name: 'Larry White', Email: 'larry.white@domain.com' },
      { user_id: 46, userName: 'samanthajones', Name: 'Samantha Jones', Email: 'samantha.jones@techcorp.com' },
      { user_id: 47, userName: 'jacobjackson', Name: 'Jacob Jackson', Email: 'jacob.jackson@example.com' },
      { user_id: 48, userName: 'hannahlee', Name: 'Hannah Lee', Email: 'hannah.lee@domain.net' },
      { user_id: 49, userName: 'matthewdavis', Name: 'Matthew Davis', Email: 'matthew.davis@webmail.org' },
      { user_id: 50, userName: 'rachelmartinez', Name: 'Rachel Martinez', Email: 'rachel.martinez@internet.io' },
    ],
    totalPosts: [
      { post_id: 1, post_comment: 'Exploring the mountains!', media_url: 'https://picsum.photos/seed/1/600/400' },
      { post_id: 2, post_comment: 'Just another day in paradise.', media_url: 'https://picsum.photos/seed/2/600/400' },
      { post_id: 3, post_comment: 'Loving this new place!', media_url: 'https://picsum.photos/seed/3/600/400' },
      { post_id: 4, post_comment: 'Adventures in the city!', media_url: 'https://picsum.photos/seed/4/600/400' },
      { post_id: 5, post_comment: 'Sunset by the beach.', media_url: 'https://picsum.photos/seed/5/600/400' },
      { post_id: 6, post_comment: 'A quiet moment.', media_url: 'https://picsum.photos/seed/6/600/400' },
      { post_id: 7, post_comment: 'Hiking through the woods.', media_url: 'https://picsum.photos/seed/7/600/400' },
      { post_id: 8, post_comment: 'A day in the life.', media_url: 'https://picsum.photos/seed/8/600/400' },
      { post_id: 9, post_comment: 'Street photography vibes.', media_url: 'https://picsum.photos/seed/9/600/400' },
      { post_id: 10, post_comment: 'Enjoying the moment.', media_url: 'https://picsum.photos/seed/10/600/400' },
      { post_id: 11, post_comment: 'Nature at its best.', media_url: 'https://picsum.photos/seed/11/600/400' },
      { post_id: 12, post_comment: 'City lights at night.', media_url: 'https://picsum.photos/seed/12/600/400' },
      { post_id: 13, post_comment: 'Wanderlust.', media_url: 'https://picsum.photos/seed/13/600/400' },
      { post_id: 14, post_comment: 'Chasing sunsets.', media_url: 'https://picsum.photos/seed/14/600/400' },
      { post_id: 15, post_comment: 'Urban exploration.', media_url: 'https://picsum.photos/seed/15/600/400' },
      { post_id: 16, post_comment: 'Life is beautiful.', media_url: 'https://picsum.photos/seed/16/600/400' },
      { post_id: 17, post_comment: 'Moments like these.', media_url: 'https://picsum.photos/seed/17/600/400' },
      { post_id: 18, post_comment: 'The great outdoors.', media_url: 'https://picsum.photos/seed/18/600/400' },
      { post_id: 19, post_comment: 'Captured memories.', media_url: 'https://picsum.photos/seed/19/600/400' },
      { post_id: 20, post_comment: 'Evening stroll.', media_url: 'https://picsum.photos/seed/20/600/400' },
      { post_id: 21, post_comment: 'A day well spent.', media_url: 'https://picsum.photos/seed/21/600/400' },
      { post_id: 22, post_comment: 'In the moment.', media_url: 'https://picsum.photos/seed/22/600/400' },
      { post_id: 23, post_comment: 'Urban adventures.', media_url: 'https://picsum.photos/seed/23/600/400' },
      { post_id: 24, post_comment: 'By the river.', media_url: 'https://picsum.photos/seed/24/600/400' },
      { post_id: 25, post_comment: 'Summer vibes.', media_url: 'https://picsum.photos/seed/25/600/400' },
      { post_id: 26, post_comment: 'Through the lens.', media_url: 'https://picsum.photos/seed/26/600/400' },
      { post_id: 27, post_comment: 'Ocean breeze.', media_url: 'https://picsum.photos/seed/27/600/400' },
      { post_id: 28, post_comment: 'Serenity.', media_url: 'https://picsum.photos/seed/28/600/400' },
      { post_id: 29, post_comment: 'Golden hour.', media_url: 'https://picsum.photos/seed/29/600/400' },
      { post_id: 30, post_comment: 'Cityscapes.', media_url: 'https://picsum.photos/seed/30/600/400' },
      { post_id: 31, post_comment: 'Finding peace.', media_url: 'https://picsum.photos/seed/31/600/400' },
      { post_id: 32, post_comment: 'New beginnings.', media_url: 'https://picsum.photos/seed/32/600/400' },
      { post_id: 33, post_comment: 'On the road.', media_url: 'https://picsum.photos/seed/33/600/400' },
      { post_id: 34, post_comment: 'The simple things.', media_url: 'https://picsum.photos/seed/34/600/400' },
      { post_id: 35, post_comment: 'Quiet reflections.', media_url: 'https://picsum.photos/seed/35/600/400' },
      { post_id: 36, post_comment: 'Lost in the moment.', media_url: 'https://picsum.photos/seed/36/600/400' },
      { post_id: 37, post_comment: 'Capturing life.', media_url: 'https://picsum.photos/seed/37/600/400' },
      { post_id: 38, post_comment: 'Joy in simplicity.', media_url: 'https://picsum.photos/seed/38/600/400' },
      { post_id: 39, post_comment: 'Dream big.', media_url: 'https://picsum.photos/seed/39/600/400' },
      { post_id: 40, post_comment: 'In the wild.', media_url: 'https://picsum.photos/seed/40/600/400' },
      { post_id: 41, post_comment: 'Urban charm.', media_url: 'https://picsum.photos/seed/41/600/400' },
      { post_id: 42, post_comment: 'Living the dream.', media_url: 'https://picsum.photos/seed/42/600/400' },
      { post_id: 43, post_comment: 'Sunshine and smiles.', media_url: 'https://picsum.photos/seed/43/600/400' },
      { post_id: 44, post_comment: 'Beneath the stars.', media_url: 'https://picsum.photos/seed/44/600/400' },
      { post_id: 45, post_comment: 'Echoes of the past.', media_url: 'https://picsum.photos/seed/45/600/400' },
      { post_id: 46, post_comment: 'Footsteps in the sand.', media_url: 'https://picsum.photos/seed/46/600/400' },
      { post_id: 47, post_comment: 'A new journey.', media_url: 'https://picsum.photos/seed/47/600/400' },
      { post_id: 48, post_comment: 'The road less traveled.', media_url: 'https://picsum.photos/seed/48/600/400' },
      { post_id: 49, post_comment: 'Moments to cherish.', media_url: 'https://picsum.photos/seed/49/600/400' },
      { post_id: 50, post_comment: 'A world of wonder.', media_url: 'https://picsum.photos/seed/50/600/400' },
    ],
    usersActive: 45,
    postsPublished: 66,
  };
  
export default sampleData